#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

error_msg="Usage: manage_my_process {start|stop|restart}"
action=$1
pid="/var/run/my_process.pid"
process_file="manage_my_process"

start()
{
	"./$process_file" &
	echo $! > "$pid"
	echo "$process_file started"
}

stop()
{
	kill -s SIGKILL "$(cat $pid)"
	rm -f "$pid"
	echo "$process_file stopped"
}

restart()
{
	if [ -e "$pid" ]
	then
		kill -s SIGKILL "$(cat $pid)"
		rm -f "$pid"
	fi
	"./$process_file" &
	echo $! > "$pid"
	echo "$process_file restarted"
}
	
case "X$action" in
	"Xstart")
		start
		;;
	"Xstop")
		stop
		;;
	"Xrestart")
		restart
		;;
	*)
		echo "$error_msg"
		;;
esac
